machine conn. check has been added in manager script

diff --git a/install/machine/usr/local/lastcontrol/manager b/install/machine/usr/local/lastcontrol/manager
--- a/install/machine/usr/local/lastcontrol/manager
+++ b/install/machine/usr/local/lastcontrol/manager
@@ -31,7 +31,7 @@ tput setaf "$BANNERCOLOR"
 cat $WDIR/doc/banner.txt
 echo ""
 tput setaf 9
-echo "    V2 Update:22"
+echo "    V2 Update:21"
 echo "    $HOSTOS - IP: $HOSTIP"
 tput setaf 8
 tput sgr0
@@ -61,7 +61,7 @@ tput setaf 1
 tput sgr0
 echo "     $BOARDMSG                                                         "
 echo "   --------------------------------------------------------------------"
-echo "    Download Reports: http://$HOSTIP/pdfreports                     "
+echo "    Download Reports: http://$HOSTIP/pdfreports                        "
 tput setaf 9
 echo ""
 echo "    -----------"
@@ -77,16 +77,25 @@ function create_system_report(){
 	tput setaf 9
 	echo "::.. Generating System Report... ..::"
 	echo ""
-	bash $CREATE systemreport $TARGETMACHINE
-	tput setaf 7
-	echo ""
-	cat $RDIR/$TARGETMACHINE-systemreport.txt
-	tput sgr 0
-	echo ""
-	
-	pandoc -s -o $PDFSTORE/$TARGETMACHINE-systemreport.pdf $RDIR/$TARGETMACHINE-systemreport.md
-	cp $PDFSTORE/$TARGETMACHINE-systemreport.pdf $PDFREPORTS/
-	pause
+	nc -z -w 2 $TARGETMACHINE 22 2>/dev/null
+	if [ "$?" = "0" ]; then
+		bash $CREATE systemreport $TARGETMACHINE
+		tput setaf 7
+		echo ""
+		cat $RDIR/$TARGETMACHINE-systemreport.txt
+		tput sgr 0
+		echo ""
+		
+		pandoc -s -o $PDFSTORE/$TARGETMACHINE-systemreport.pdf $RDIR/$TARGETMACHINE-systemreport.md
+		cp $PDFSTORE/$TARGETMACHINE-systemreport.pdf $PDFREPORTS/
+		pause
+	else
+		tput setaf 2
+		echo "Could not reach $TARGETMACHINE"
+		tput sgr 0
+		echo -e
+		pause
+	fi
 }
 
 function create_service_report(){
