kernelreport function updated for ssh-key check

diff --git a/lastcontrol/manager b/lastcontrol/manager
--- a/lastcontrol/manager
+++ b/lastcontrol/manager
@@ -449,24 +449,39 @@ function create_inventory_report(){
 function create_update_report(){
 	read -p "Enter the Machine Hostname : " TARGETMACHINE
 	echo ""
-	$RED
-	echo "::.. Generating System Update Report... ..::"
-
-	nc -z -w 2 $TARGETMACHINE 22 2>/dev/null
-	if [ "$?" = "0" ]; then
-		bash $RPTLIN updatereport $TARGETMACHINE
-		tput setaf 7
-		echo ""
-		cat $RDIR/$TARGETMACHINE/$TARGETMACHINE-updatereport.txt
-		tput sgr 0
-		echo ""
-
-		echo "Info: Generated $TARGETMACHINE Update Report" > $BOARDFILE
-		pause
-	else
-		tput setaf 2
-		echo "Could not reach $TARGETMACHINE from Port 22"
-		tput sgr 0
+	ssh -p22 -i /root/.ssh/lastcontrol -o "StrictHostKeyChecking no" root@$TARGETMACHINE &
+        PID=$!
+        sleep 1
+        kill $PID
+	if [ "$?" = 1 ]; then
+		$RED
+		echo "::.. Generating System Update Report... ..::"
+		nc -z -w 2 $TARGETMACHINE 22 2>/dev/null
+		if [ "$?" = "0" ]; then
+			bash $RPTLIN updatereport $TARGETMACHINE
+			tput setaf 7
+			echo ""
+			cat $RDIR/$TARGETMACHINE/$TARGETMACHINE-updatereport.txt
+			tput sgr 0
+			echo ""
+			echo "Info: Generated $TARGETMACHINE Update Report" > $BOARDFILE
+			pause
+		else
+			tput setaf 2
+			echo "Could not reach $TARGETMACHINE from Port 22"
+			tput sgr 0
+			echo -e
+			pause
+		fi
+	else # The password prompt returns 0. In this check, else also works outside of 0.
+		$RED
+		echo -e
+		echo "[ Error ]"
+		echo "LastControl SSH-Key Not Found on $TARGETMACHINE"
+		echo -e
+		$GREEN
+		echo "You can add the LastControl SSH-Key from menu 40.Add SSH-Key"
+		$NOCOL
 		echo -e
 		pause
 	fi
@@ -475,31 +490,45 @@ function create_update_report(){
 function create_kernel_report(){
 	read -p "Enter the Machine Hostname : " TARGETMACHINE
 	echo ""
-	$RED
-	echo "::.. Generating Kernel Report... ..::"
-	echo ""
-
-	nc -z -w 2 $TARGETMACHINE 22 2>/dev/null
-	if [ "$?" = "0" ]; then
-		bash $RPTLIN kernelreport $TARGETMACHINE
-		tput setaf 7
+	ssh -p22 -i /root/.ssh/lastcontrol -o "StrictHostKeyChecking no" root@$TARGETMACHINE &
+        PID=$!
+        sleep 1
+        kill $PID
+	if [ "$?" = 1 ]; then
+		$RED
+		echo "::.. Generating Kernel Report... ..::"
 		echo ""
-		cat $RDIR/$TARGETMACHINE/$TARGETMACHINE-kernelreport.txt
-		tput sgr 0
-		echo ""
-
-		pandoc -s -o $PDFSTORE/$TARGETMACHINE-kernelreport.pdf $RDIR/$TARGETMACHINE/$TARGETMACHINE-kernelreport.md
-		mkdir -p $PDFREPORTS/$TARGETMACHINE
-		cp $PDFSTORE/$TARGETMACHINE-kernelreport.pdf $PDFREPORTS/$TARGETMACHINE/
-		cp $RDIR/$TARGETMACHINE/$TARGETMACHINE-kernelreport.txt $PDFREPORTS/$TARGETMACHINE/
-		cp $RDIR/$TARGETMACHINE/$TARGETMACHINE-kernelreport.json $PDFREPORTS/$TARGETMACHINE/
-
-		echo "Info: Generated $TARGETMACHINE Kernel Report" > $BOARDFILE
-		pause
-	else
-		tput setaf 2
-		echo "Could not reach $TARGETMACHINE from Port 22"
-		tput sgr 0
+		nc -z -w 2 $TARGETMACHINE 22 2>/dev/null
+		if [ "$?" = "0" ]; then
+			bash $RPTLIN kernelreport $TARGETMACHINE
+			tput setaf 7
+			echo ""
+			cat $RDIR/$TARGETMACHINE/$TARGETMACHINE-kernelreport.txt
+			tput sgr 0
+			echo ""
+			pandoc -s -o $PDFSTORE/$TARGETMACHINE-kernelreport.pdf $RDIR/$TARGETMACHINE/$TARGETMACHINE-kernelreport.md
+			mkdir -p $PDFREPORTS/$TARGETMACHINE
+			cp $PDFSTORE/$TARGETMACHINE-kernelreport.pdf $PDFREPORTS/$TARGETMACHINE/
+			cp $RDIR/$TARGETMACHINE/$TARGETMACHINE-kernelreport.txt $PDFREPORTS/$TARGETMACHINE/
+			cp $RDIR/$TARGETMACHINE/$TARGETMACHINE-kernelreport.json $PDFREPORTS/$TARGETMACHINE/
+			echo "Info: Generated $TARGETMACHINE Kernel Report" > $BOARDFILE
+			pause
+		else
+			tput setaf 2
+			echo "Could not reach $TARGETMACHINE from Port 22"
+			tput sgr 0
+			echo -e
+			pause
+		fi
+	else # The password prompt returns 0. In this check, else also works outside of 0.
+		$RED
+		echo -e
+		echo "[ Error ]"
+		echo "LastControl SSH-Key Not Found on $TARGETMACHINE"
+		echo -e
+		$GREEN
+		echo "You can add the LastControl SSH-Key from menu 40.Add SSH-Key"
+		$NOCOL
 		echo -e
 		pause
 	fi
