manager script updated for access control in inventory function

diff --git a/lastcontrol/manager b/lastcontrol/manager
--- a/lastcontrol/manager
+++ b/lastcontrol/manager
@@ -291,21 +291,30 @@ function create_inventory_report(){
         tput setaf 9
         echo "::.. Generating Hardware Inventory Report... ..::"
         echo ""
-        bash $RPTLIN inventoryreport $TARGETMACHINE
-        tput setaf 7
-        echo ""
-        cat $RDIR/$TARGETMACHINE/$TARGETMACHINE-inventoryreport.txt
-        tput sgr 0
-        echo ""
-
-        pandoc -s -o $PDFSTORE/$TARGETMACHINE-inventoryreport.pdf $RDIR/$TARGETMACHINE/$TARGETMACHINE-inventoryreport.md
-	mkdir -p $PDFREPORTS/$TARGETMACHINE
-	cp $PDFSTORE/$TARGETMACHINE-inventoryreport.pdf $PDFREPORTS/$TARGETMACHINE/
-	cp $RDIR/$TARGETMACHINE/$TARGETMACHINE-inventoryreport.txt $PDFREPORTS/$TARGETMACHINE/
-	cp $RDIR/$TARGETMACHINE/$TARGETMACHINE-inventoryreport.json $PDFREPORTS/$TARGETMACHINE/
+	nc -z -w 2 $TARGETMACHINE 22 2>/dev/null
+	if [ "$?" = "0" ]; then
+		bash $RPTLIN inventoryreport $TARGETMACHINE
+		tput setaf 7
+		echo ""
+		cat $RDIR/$TARGETMACHINE/$TARGETMACHINE-inventoryreport.txt
+		tput sgr 0
+		echo ""
+		
+		pandoc -s -o $PDFSTORE/$TARGETMACHINE-inventoryreport.pdf $RDIR/$TARGETMACHINE/$TARGETMACHINE-inventoryreport.md
+		mkdir -p $PDFREPORTS/$TARGETMACHINE
+		cp $PDFSTORE/$TARGETMACHINE-inventoryreport.pdf $PDFREPORTS/$TARGETMACHINE/
+		cp $RDIR/$TARGETMACHINE/$TARGETMACHINE-inventoryreport.txt $PDFREPORTS/$TARGETMACHINE/
+		cp $RDIR/$TARGETMACHINE/$TARGETMACHINE-inventoryreport.json $PDFREPORTS/$TARGETMACHINE/
 	
-	echo "Info: Generated $TARGETMACHINE Inventory Report" > $BOARDFILE
-        pause
+		echo "Info: Generated $TARGETMACHINE Inventory Report" > $BOARDFILE
+		pause
+	else
+		tput setaf 2
+		echo "Could not reach $TARGETMACHINE from Port 22"
+		tput sgr 0
+		echo -e
+		pause
+	fi
 }
 
 function create_update_report(){
